# Generated by Django 4.2.1 on 2023-05-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("PR", "Происшествия"),
                    ("POL", "Политика"),
                    ("SP", "Спорт"),
                    ("KU", "Культура"),
                ],
                default="SP",
                max_length=15,
                verbose_name="Категория",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(verbose_name="Содержимое"),
        ),
        migrations.AlterField(
            model_name="post",
            name="created",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.BooleanField(default=True, verbose_name="Статус публикации"),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Заголовок"),
        ),
    ]
