# Generated by Django 4.2.1 on 2023-05-17 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_category_alter_post_content_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={
                "verbose_name": "Запись блога",
                "verbose_name_plural": "Записи блога",
            },
        ),
    ]
